### ISSUE TITLE
On return from OPAC not all own courses are visible

### ISSUE THREAD

**Issue by mypa** [digisem/digisem#9]
This bug is only relevant for people using the alternative to add a digisem to a course:

Expected:
1. Select a book in the OPAC and continue to the moodle digisem plugin
2. In the 'bridge' you see all your courses
3. You select one of the courses and add the digisem to the course thereafter

Actually:
2. Not all own courses are available in the 'bridge'
This applies only for non-admin users

**Comment by mypa** [comment]
Please check if this bug is up to date

**Comment by ni-to** [comment]
Bug not reproducible. Some notes on this issue:

1) Admin users:
- If you are using an admin account you can edit any moodle course in general. But the Digisem bridge.php uses an API call to get all courses the current user is enrolled in (enrol_get_my_courses()).
- Thus to use the Digisem plugin as admin user you need to enroll in any course you want to add items using the Digisem plug-in.

2) Non-admin users:
- As mentioned in 1. the bridge.php uses the API call enrol_get_my_courses() to get a list of all courses the current user in enrolled in. 
- For each of this courses the bridge.php checks if the current user has the right to update the course. Only courses where this right is given are displayed in the list showed to the user.

I've done the following tests on this issue:
- Using an admin account which is not enrolled in any course: bridge.php displays an error message -> OK
- Using an admin account which is enrolled in course A: bridge.php displays a list containing only course A -> OK
- Using an admin account which is enrolled in course A and course B: bridge.php displays a list containing only course A and course B -> OK
- Using an non-admin account which is trainer in course A and participant in course B: bridge.php displayes a list containing only course A -> OK
- Using an non-admin account which is only participant in course A: bridge.php displays error message -> OK
- Using an non-admin account which is trainer in course A and trainer in course B: bridge.php displays a list containing only course A and course B -> OK
